<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <WarningLevel>9999</WarningLevel>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <WarningLevel>9999</WarningLevel>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Models\AppDbContext.cs" />
    <Compile Remove="Models\Repository\ISpielerRepository.cs" />
    <Compile Remove="Models\SpielerRepository.cs" />
    <Compile Remove="Models\TabelleRepository.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="Docker.DotNet" Version="3.125.15" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.1.5" />
    <PackageReference Include="Radzen.Blazor" Version="4.32.8" />
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LigaManagement.Models\LigaManagement.Models.csproj" />
    <ProjectReference Include="..\Ligamanager.Components\Ligamanager.Components.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Errors\" />
    <Folder Include="logs\" />
  </ItemGroup>


</Project>
