// <auto-generated />
using System;
using LigaManagement.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LigaManagement.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231108085702_Spieltage")]
    partial class Spieltage
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LigaManagement.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("LigaManagement.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfBrith")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("LigaManagement.Models.Liga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Absteiger")
                        .HasColumnType("int");

                    b.Property<string>("Aktiv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Erstaustragung")
                        .HasColumnType("datetime2");

                    b.Property<string>("Liganame")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Verband")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ligen");
                });

            modelBuilder.Entity("LigaManagement.Models.Spieltag", b =>
                {
                    b.Property<int>("SpieltagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Abgeschlossen")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("LigaID")
                        .HasColumnType("int");

                    b.Property<string>("Ort")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Saison")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SaisonID")
                        .HasColumnType("int");

                    b.Property<string>("Schiedrichter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpieltagNr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tore1_Nr")
                        .HasColumnType("int");

                    b.Property<int>("Tore2_Nr")
                        .HasColumnType("int");

                    b.Property<string>("Verein1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Verein1_Nr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Verein2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Verein2_Nr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Zuschauer")
                        .HasColumnType("int");

                    b.HasKey("SpieltagId");

                    b.ToTable("Spieltage");
                });

            modelBuilder.Entity("LigaManagement.Models.Verein", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Erfolge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fassungsvermoegen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gegruendet")
                        .HasColumnType("int");

                    b.Property<string>("Stadion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VereinNr")
                        .HasColumnType("int");

                    b.Property<string>("Vereinsname1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vereinsname2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vereine");
                });

            modelBuilder.Entity("LigaManagerManagement.Models.Saison", b =>
                {
                    b.Property<int>("SaisonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Abgeschlossen")
                        .HasColumnType("bit");

                    b.Property<bool>("Aktuell")
                        .HasColumnType("bit");

                    b.Property<int>("LigaID")
                        .HasColumnType("int");

                    b.Property<string>("Liganame")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Saisonname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SaisonID");

                    b.ToTable("Saisonen");
                });

            modelBuilder.Entity("LigaManagement.Models.Employee", b =>
                {
                    b.HasOne("LigaManagement.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
