USE [LigaManager]
--IF OBJECT_ID(N'dbo.Spieler', N'U') IS NULL

CREATE TABLE [dbo].Kader(
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[SpielerName] [nvarchar](100) NOT NULL,
	[Vorname] [nvarchar](100) NOT NULL,
	[Geburtstag] [date] NOT NULL,
	[Position] [nvarchar](50) NOT NULL,
	[PositionsNr] [int]  NOT NULL,
	[Groesse] [decimal],
	[Gewicht] [decimal],
	[Laenderspiele] [int],	
	[LaenderspieleTore] [int],	
	[VereinNr] [int] NOT NULL,	
	[LandID] [nvarchar](100),
	[SaisonID] [int],	
	[LigaID] [int],	
	[Rueckennummer] [int],
	[Position] [nvarchar](50) NOT NULL,
	[Einsaetze] [int]  NOT NULL,
	[Spielminuten] [int],
	[Tore] [int],
	[Abloesesumme] [decimal],
	[Image] [image],
	[ImVereinSeit] [date],
	[Aktiv] [bit],
) 
GO

--IF OBJECT_ID(N'dbo.SpielerVerein', N'U') IS NULL
CREATE TABLE [dbo].KaderVerein(
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[SpielerID] [int] NOT NULL,	
	[VereinNr] [int] NOT NULL,	
	[DateVon] [date],
	[DateBis] [date],
) 
GO

SET IDENTITY_INSERT [dbo].Kader ON 
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (53, N'Goosens', N'Robin', CAST(N'1994-07-05' AS Date), NULL, NULL, NULL, NULL, 4, N'57', 1, 1, 6, 19, 300, 5, NULL, NULL, CAST(N'2023-07-01' AS Date), 1, NULL, 1)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (54, N'Hollerbach', N'Hollerbach', CAST(N'2001-05-17' AS Date), NULL, NULL, NULL, NULL, 4, N'57', 1, 1, 16, 15, 300, 3, NULL, NULL, CAST(N'2023-07-01' AS Date), 1, NULL, 4)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (8, N'Undav', N'Deniz', CAST(N'1995-04-14' AS Date), NULL, NULL, NULL, NULL, 16, N'57', 1, 1, 26, 18, 487, 14, NULL, NULL, CAST(N'2023-07-01' AS Date), 1, NULL, 4)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (9, N'Guirassy', N'Serhou', CAST(N'1997-04-14' AS Date), NULL, NULL, NULL, NULL, 16, N'57', 1, 1, 9, 19, 400, 18, NULL, NULL, CAST(N'2022-08-30' AS Date), 1, NULL, 4)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (10, N'Führich', N'Chris', CAST(N'1997-04-14' AS Date), NULL, NULL, NULL, NULL, 16, N'57', 1, 1, 11, 19, 800, 6, NULL, NULL, CAST(N'2021-07-01' AS Date), 1, NULL, 4)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (11, N'Mittelstädt', N'Maximillian', CAST(N'1997-04-14' AS Date), NULL, NULL, NULL, NULL, 16, N'57', 1, 1, 7, 19, 300, 2, NULL, NULL, CAST(N'2023-07-01' AS Date), 1, NULL, 2)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (12, N'Millot', N'Enzo', CAST(N'2002-07-17' AS Date), NULL, NULL, NULL, NULL, 16, N'57', 1, 1, 10, 19, 300, 4, NULL, NULL, CAST(N'2023-07-01' AS Date), 1, NULL, 3)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (13, N'Silas', N'', CAST(N'1998-10-06' AS Date), NULL, NULL, NULL, NULL, 16, N'57', 1, 1, 14, 16, 300, 3, NULL, NULL, CAST(N'2019-07-01' AS Date), 1, NULL, 4)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (14, N'Leweling', N'Jamie', CAST(N'2001-02-26' AS Date), NULL, NULL, NULL, NULL, 16, N'57', 1, 1, 18, 18, 300, 2, NULL, NULL, CAST(N'2023-07-01' AS Date), 1, NULL, 4)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (15, N'Anton', N'Waldemar', CAST(N'1996-07-20' AS Date), NULL, NULL, NULL, NULL, 16, N'57', 1, 1, 2, 19, 300, 0, NULL, NULL, CAST(N'2020-07-01' AS Date), 1, NULL, 2)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (16, N'Ito', N'Hikori', CAST(N'1999-05-12' AS Date), NULL, NULL, NULL, NULL, 16, N'57', 1, 1, 21, 19, 300, 0, NULL, NULL, CAST(N'2021-07-01' AS Date), 1, NULL, 2)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (17, N'Beier', N'Maximilian ', CAST(N'2002-10-17' AS Date), NULL, NULL, NULL, NULL, 12, N'57', 1, 1, 14, 19, 300, 8, NULL, NULL, CAST(N'2023-07-01' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (18, N'Kramaric', N'Andrej ', CAST(N'1991-06-19' AS Date), NULL, NULL, NULL, NULL, 12, N'57', 1, 1, 27, 21, 300, 8, NULL, NULL, CAST(N'2016-06-19' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (19, N'Weghorst', N'Wout', CAST(N'1992-08-07' AS Date), NULL, NULL, NULL, NULL, 12, N'57', 1, 1, 10, 17, 300, 5, NULL, NULL, CAST(N'2023-01-03' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (20, N'Kabak', N'Ozan', CAST(N'2000-03-25' AS Date), NULL, NULL, NULL, NULL, 12, N'57', 1, 1, 5, 17, 300, 2, NULL, NULL, CAST(N'2022-07-22' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (21, N'Prömel', N'Grischa', CAST(N'1995-01-09' AS Date), NULL, NULL, NULL, NULL, 12, N'57', 1, 1, 6, 17, 300, 3, NULL, NULL, CAST(N'2022-07-01' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (22, N'Openda', N'Lous', CAST(N'2000-02-16' AS Date), NULL, NULL, NULL, NULL, 3, N'57', 1, 1, 17, 21, 300, 16, NULL, NULL, CAST(N'2023-07-01' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (23, N'Sesko', N'Benjamin ', CAST(N'2003-05-31' AS Date), NULL, NULL, NULL, NULL, 3, N'57', 1, 1, 30, 18, 300, 6, NULL, NULL, CAST(N'2023-07-01' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (24, N'Xavi', N'', CAST(N'2003-04-21' AS Date), NULL, NULL, NULL, NULL, 3, N'57', 1, 1, 20, 21, 300, 6, NULL, NULL, CAST(N'2023-07-01' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (25, N'Füllkrug', N'Niclas', CAST(N'1993-02-09' AS Date), NULL, NULL, NULL, NULL, 2, N'57', 1, 1, 9, 21, 300, 10, NULL, NULL, CAST(N'2023-01-03' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (26, N'Malen', N'Donyell ', CAST(N'1999-01-19' AS Date), NULL, NULL, NULL, NULL, 2, N'57', 1, 1, 10, 21, 300, 9, NULL, NULL, CAST(N'2021-07-27' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (27, N'Vagnoman', N'Josuha', CAST(N'2000-12-11' AS Date), NULL, NULL, NULL, NULL, 16, N'57', 1, 1, 19, 18, 300, 0, NULL, NULL, CAST(N'2023-07-01' AS Date), 1, NULL, 2)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (28, N'Nübel ', N'Alexander', CAST(N'1996-09-30' AS Date), NULL, NULL, NULL, NULL, 16, N'57', 1, 1, 33, 20, 300, 0, NULL, NULL, CAST(N'2023-07-01' AS Date), 1, NULL, 1)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (29, N'Stenzel', N'Pascal', CAST(N'1996-03-20' AS Date), NULL, NULL, NULL, NULL, 16, N'57', 1, 1, 15, 15, 300, 0, NULL, NULL, CAST(N'2019-07-01' AS Date), 1, NULL, 2)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (30, N'Zagadou', N'Dan-Axel', CAST(N'1999-06-03' AS Date), NULL, NULL, NULL, NULL, 16, N'57', 1, 1, 23, 19, 300, 1, NULL, NULL, CAST(N'2022-09-19' AS Date), 1, NULL, 2)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (31, N'Jeong', N'Woo-Yeong', CAST(N'1999-09-20' AS Date), NULL, NULL, NULL, NULL, 16, N'57', 1, 1, 23, 15, 300, 0, NULL, NULL, CAST(N'2020-07-01' AS Date), 1, NULL, 3)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (32, N'Stiller', N'Angelo', CAST(N'2001-04-04' AS Date), NULL, NULL, NULL, NULL, 16, N'57', 1, 1, 23, 20, 300, 0, NULL, NULL, CAST(N'2023-07-01' AS Date), 1, NULL, 2)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (33, N'Dahoud', N'Mo', CAST(N'1996-01-01' AS Date), NULL, NULL, NULL, NULL, 16, N'57', 1, 1, 5, 4, 300, 1, NULL, NULL, CAST(N'2024-01-01' AS Date), 1, NULL, 3)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (34, N'Karazor', N'Atakan', CAST(N'1996-10-13' AS Date), NULL, NULL, NULL, NULL, 16, N'57', 1, 1, 16, 20, 300, 0, NULL, NULL, CAST(N'2019-07-01' AS Date), 1, NULL, 3)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (35, N'Milosevic', N'Jovan', CAST(N'2005-07-31' AS Date), NULL, NULL, NULL, NULL, 16, N'57', 1, 1, 16, 5, 300, 0, NULL, NULL, CAST(N'2023-07-01' AS Date), 1, NULL, 4)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (36, N'Egloff', N'Lilian', CAST(N'2002-08-30' AS Date), NULL, NULL, NULL, NULL, 16, N'57', 1, 1, 25, 5, 300, 0, NULL, NULL, CAST(N'2012-07-01' AS Date), 1, NULL, 3)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (37, N'Rouault', N'Anthony', CAST(N'2002-07-31' AS Date), NULL, NULL, NULL, NULL, 16, N'57', 1, 1, 29, 16, 300, 0, NULL, NULL, CAST(N'2023-07-01' AS Date), 1, NULL, 2)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (38, N'Stergiou', N'Leonidas', CAST(N'2003-07-31' AS Date), NULL, NULL, NULL, NULL, 16, N'57', 1, 1, 20, 5, 300, 0, NULL, NULL, CAST(N'2023-07-01' AS Date), 1, NULL, 2)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (39, N'Boniface', N'Viktor', CAST(N'2000-12-23' AS Date), NULL, NULL, NULL, NULL, 6, N'57', 1, 1, 22, 16, 300, 10, NULL, NULL, CAST(N'2023-07-01' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (40, N'Wirtz', N'Florian', CAST(N'2003-05-03' AS Date), NULL, NULL, NULL, NULL, 6, N'57', 1, 1, 10, 21, 300, 5, NULL, NULL, CAST(N'2023-07-01' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (41, N'Grimaldo', N'Alejandro ', CAST(N'1995-09-20' AS Date), NULL, NULL, NULL, NULL, 6, N'57', 1, 1, 20, 21, 300, 8, NULL, NULL, CAST(N'2023-07-01' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (42, N'Skarke', N'Tim', CAST(N'1996-09-07' AS Date), NULL, NULL, NULL, NULL, 17, N'57', 1, 1, 27, 19, 300, 6, NULL, NULL, CAST(N'2023-07-01' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (43, N'Pfeiffer', N'Luca', CAST(N'1996-08-20' AS Date), NULL, NULL, NULL, NULL, 17, N'57', 1, 1, 24, 19, 300, 1, NULL, NULL, CAST(N'2023-07-01' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (44, N'Kempe', N'Tobias', CAST(N'1996-08-20' AS Date), NULL, NULL, NULL, NULL, 17, N'57', 1, 1, 11, 16, 300, 3, NULL, NULL, CAST(N'2017-07-07' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (45, N'Demirovic', N'Ermedin ', CAST(N'1998-03-25' AS Date), NULL, NULL, NULL, NULL, 15, N'57', 1, 1, 9, 21, 300, 12, NULL, NULL, CAST(N'2017-07-07' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (46, N'Tietz', N'Philipp', CAST(N'1997-07-09' AS Date), NULL, NULL, NULL, NULL, 15, N'57', 1, 1, 21, 21, 300, 5, NULL, NULL, CAST(N'2023-07-12' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (47, N'Reus', N'Marco', CAST(N'1989-05-31' AS Date), NULL, NULL, NULL, NULL, 2, N'57', 1, 1, 11, 16, 300, 4, NULL, NULL, CAST(N'2012-01-07' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (48, N'Sabitzer', N'Marcel', CAST(N'1994-03-17' AS Date), NULL, NULL, NULL, NULL, 2, N'57', 1, 1, 20, 16, 300, 2, NULL, NULL, CAST(N'2023-01-03' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (49, N'Brandt', N'Julian', CAST(N'1996-05-02' AS Date), NULL, NULL, NULL, NULL, 2, N'57', 1, 1, 19, 19, 300, 6, NULL, NULL, CAST(N'2019-07-01' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (50, N'Beljo', N'Dion Drena', CAST(N'2002-03-01' AS Date), NULL, NULL, NULL, NULL, 15, N'57', 1, 1, 7, 21, 300, 2, NULL, NULL, CAST(N'2023-01-13' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (51, N'Engels', N'Arne', CAST(N'2003-09-09' AS Date), NULL, NULL, NULL, NULL, 15, N'57', 1, 1, 27, 21, 300, 2, NULL, NULL, CAST(N'2023-01-03' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (52, N'Gouweleeuw', N'Jeffrey ', CAST(N'1991-07-10' AS Date), NULL, NULL, NULL, NULL, 15, N'57', 1, 1, 6, 21, 300, 0, NULL, NULL, CAST(N'2016-01-09' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (55, N'Volland ', N'Kevin', CAST(N'1992-07-30' AS Date), NULL, NULL, NULL, NULL, 4, N'57', 1, 1, 16, 15, 300, 2, NULL, NULL, CAST(N'2023-07-01' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (56, N'Doekhi', N'Danilo', CAST(N'1998-06-30' AS Date), NULL, NULL, NULL, NULL, 4, N'57', 1, 1, 5, 11, 300, 2, NULL, NULL, CAST(N'2023-07-01' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (57, N'Baku', N'Ridle', CAST(N'1998-06-08' AS Date), NULL, NULL, NULL, NULL, 8, N'57', 1, 1, 5, 20, 300, 0, NULL, NULL, CAST(N'2020-10-07' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (58, N'Wind', N'Jonas', CAST(N'1999-02-07' AS Date), NULL, NULL, NULL, NULL, 8, N'57', 1, 1, 5, 21, 300, 9, NULL, NULL, CAST(N'2022-01-31' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (59, N'Majer', N'Lovro', CAST(N'1998-10-17' AS Date), NULL, NULL, NULL, NULL, 8, N'57', 1, 1, 5, 21, 300, 4, NULL, NULL, CAST(N'2023-07-01' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (60, N'Tomas', N'Tiago', CAST(N'2002-06-16' AS Date), NULL, NULL, NULL, NULL, 8, N'57', 1, 1, 5, 17, 300, 1, NULL, NULL, CAST(N'2023-07-01' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (61, N'Gregoritsch', N'Michael', CAST(N'1994-04-18' AS Date), NULL, NULL, NULL, NULL, 5, N'57', 1, 1, 38, 19, 300, 3, NULL, NULL, CAST(N'2022-07-18' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (62, N'Höler', N'Lukas', CAST(N'1994-07-10' AS Date), CAST(2 AS Decimal(18, 0)), CAST(84 AS Decimal(18, 0)), NULL, NULL, 5, N'57', 1, 1, 38, 21, 300, 6, NULL, NULL, CAST(N'2018-01-01' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (63, N'Grifo', N'Vincenzo ', CAST(N'1993-04-07' AS Date), CAST(2 AS Decimal(18, 0)), CAST(84 AS Decimal(18, 0)), NULL, NULL, 5, N'57', 1, 1, 32, 19, 300, 5, NULL, NULL, CAST(N'2019-09-02' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (64, N'Nürnberger', N'Fabian', CAST(N'1999-07-28' AS Date), NULL, NULL, NULL, NULL, 17, N'57', 1, 1, 15, 15, 300, 1, NULL, NULL, CAST(N'2023-07-01' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (65, N'Klarer', N'Christoph ', CAST(N'2000-06-14' AS Date), NULL, NULL, NULL, NULL, 17, N'57', 1, 1, 15, 19, 300, 1, NULL, NULL, CAST(N'2023-07-18' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (66, N'Holland', N'Fabian', CAST(N'1990-07-11' AS Date), NULL, NULL, NULL, NULL, 17, N'57', 1, 1, 32, 17, 300, 0, NULL, NULL, CAST(N'2014-07-01' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (67, N'Schuhen', N'Marcel', CAST(N'1993-07-13' AS Date), NULL, NULL, NULL, NULL, 17, N'57', 1, 1, 1, 20, 300, 0, NULL, NULL, CAST(N'2019-07-01' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (68, N'Bader', N'Matthias ', CAST(N'1993-07-13' AS Date), NULL, NULL, NULL, NULL, 17, N'57', 1, 1, 26, 20, 300, 0, NULL, NULL, CAST(N'2020-01-31' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (69, N'Polter', N'Sebastian', CAST(N'1991-04-01' AS Date), NULL, NULL, NULL, NULL, 17, N'57', 1, 1, 40, 1, 300, 0, NULL, NULL, CAST(N'2024-02-01' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (70, N'Zimmermann', N'Christoph ', CAST(N'1991-04-01' AS Date), NULL, NULL, NULL, NULL, 17, N'57', 1, 1, 4, 1, 300, 0, NULL, NULL, CAST(N'2022-07-22' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (71, N'Müller', N'Jannik ', CAST(N'1994-01-18' AS Date), NULL, NULL, NULL, NULL, 17, N'57', 1, 1, 20, 8, 300, 0, NULL, NULL, CAST(N'2021-07-01' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (72, N'Karic', N'Emir', CAST(N'1997-06-09' AS Date), NULL, NULL, NULL, NULL, 17, N'57', 1, 1, 14, 14, 300, 0, NULL, NULL, CAST(N'2021-07-01' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (73, N'Seydel', N'Aaron ', CAST(N'1996-02-07' AS Date), NULL, NULL, NULL, NULL, 17, N'57', 1, 1, 28, 7, 300, 1, NULL, NULL, CAST(N'2021-07-01' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (74, N'Frimpong', N'Jeremy', CAST(N'2000-12-23' AS Date), NULL, NULL, NULL, NULL, 6, N'57', 1, 1, 22, 21, 300, 7, NULL, NULL, CAST(N'2021-01-27' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (75, N'Bredlow', N'Fabian', CAST(N'1995-03-02' AS Date), NULL, NULL, NULL, NULL, 16, N'57', 1, 1, 1, 2, 300, 0, NULL, NULL, CAST(N'2019-07-01' AS Date), 1, N'Torhüter                                          ', 1)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (76, N'Nicolas', N'Moritz', CAST(N'1997-10-21' AS Date), NULL, NULL, NULL, NULL, 10, N'57', 1, 1, 33, 20, 300, 0, NULL, NULL, CAST(N'2023-07-01' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (77, N'Plea', N'Alassane ', CAST(N'1993-03-10' AS Date), NULL, NULL, NULL, NULL, 10, N'57', 1, 1, 14, 0, 300, 7, NULL, NULL, CAST(N'2018-07-13' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (78, N'Reitz', N'Rocco ', CAST(N'2002-05-29' AS Date), NULL, NULL, NULL, NULL, 10, N'57', 1, 1, 27, 22, 300, 4, NULL, NULL, CAST(N'2023-07-01' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (79, N'Cvancara', N'Tomas', CAST(N'2000-08-13' AS Date), NULL, NULL, NULL, NULL, 10, N'57', 1, 1, 31, 0, NULL, 4, NULL, NULL, CAST(N'2023-07-01' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (80, N'Siebatcheu', N'Jordan', CAST(N'1996-04-26' AS Date), NULL, NULL, NULL, NULL, 10, N'57', 1, 1, 13, 16, 300, 4, NULL, NULL, CAST(N'2023-08-31' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (83, N'Paciencia', N'Gonzalo', CAST(N'1994-08-01' AS Date), NULL, NULL, NULL, NULL, 14, N'57', 1, 1, 9, 13, 300, 3, NULL, NULL, CAST(N'2023-09-01' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (84, N'Schwäbe', N'Marvin', CAST(N'1995-04-25' AS Date), NULL, NULL, NULL, NULL, 11, N'57', 1, 1, 1, 22, 300, 0, NULL, NULL, CAST(N'2021-07-01' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (85, N'Carstensen', N'Rasmus', CAST(N'2000-11-10' AS Date), NULL, NULL, NULL, NULL, 11, N'57', 1, 1, 18, 18, 300, 0, NULL, NULL, CAST(N'2023-08-04' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (86, N'Chabot', N'Julian', CAST(N'1998-02-12' AS Date), NULL, NULL, NULL, NULL, 11, N'57', 1, 1, 24, 20, 300, 0, NULL, NULL, CAST(N'2022-01-26' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (87, N'Selke', N'Davie', CAST(N'1995-01-20' AS Date), NULL, NULL, NULL, NULL, 11, N'57', 1, 1, 27, 15, 300, 5, NULL, NULL, CAST(N'2023-01-02' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (88, N'Kainz', N'Florian', CAST(N'1992-10-24' AS Date), NULL, NULL, NULL, NULL, 11, N'57', 1, 1, 11, 22, 300, 3, NULL, NULL, CAST(N'2019-01-18' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (89, N'Finkgräfe', N'Max', CAST(N'2004-03-27' AS Date), NULL, NULL, NULL, NULL, 11, N'57', 1, 1, 35, 14, 300, 1, NULL, NULL, CAST(N'2021-07-01' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (90, N'Ljubicic', N'Dejan', CAST(N'1997-10-08' AS Date), NULL, NULL, NULL, NULL, 11, N'57', 1, 1, 7, 21, 300, 0, NULL, NULL, CAST(N'2021-07-01' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (91, N'Alidou', N'Faride', CAST(N'2001-07-18' AS Date), NULL, NULL, NULL, NULL, 11, N'57', 1, 1, 40, 15, 300, 2, NULL, NULL, CAST(N'2023-08-21' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (92, N'Waldschmidt', N'Luca', CAST(N'1996-05-19' AS Date), NULL, NULL, NULL, NULL, 11, N'57', 1, 1, 9, 15, 300, 2, NULL, NULL, CAST(N'2023-07-01' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (93, N'Uth', N'Marc', CAST(N'1991-08-24' AS Date), NULL, NULL, NULL, NULL, 11, N'57', 1, 1, 13, 7, 300, 0, NULL, NULL, CAST(N'2021-07-01' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (94, N'Tigges', N'Stefan', CAST(N'1998-07-31' AS Date), NULL, NULL, NULL, NULL, 11, N'57', 1, 1, 21, 15, 300, 0, NULL, NULL, CAST(N'2022-07-01' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (95, N'Huseinbasic', N'Denis', CAST(N'2001-01-03' AS Date), NULL, NULL, NULL, NULL, 11, N'57', 1, 1, 8, 17, 300, 0, NULL, NULL, CAST(N'2022-07-01' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (98, N'Heintz', N'Dominique ', CAST(N'1993-08-15' AS Date), NULL, NULL, NULL, NULL, 11, N'57', 1, 1, 3, 8, 300, 0, NULL, NULL, CAST(N'2023-08-31' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (99, N'Hübers', N'Timo', CAST(N'1996-07-20' AS Date), NULL, NULL, NULL, NULL, 11, N'57', 1, 1, 4, 21, 300, 0, NULL, NULL, CAST(N'2021-07-01' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (100, N'Schmitz', N'Benno', CAST(N'1994-11-17' AS Date), NULL, NULL, NULL, NULL, 11, N'57', 1, 1, 2, 14, 300, 0, NULL, NULL, CAST(N'2018-07-01' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (101, N'Paqarada', N'Leart', CAST(N'1994-10-08' AS Date), NULL, NULL, NULL, NULL, 11, N'57', 1, 1, 17, 12, 300, 0, NULL, NULL, CAST(N'2023-07-01' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (102, N'Kilian', N'Luca', CAST(N'1999-09-01' AS Date), NULL, NULL, NULL, NULL, 11, N'57', 1, 1, 15, 11, 300, 0, NULL, NULL, CAST(N'2021-08-24' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (103, N'Martel', N'Eric', CAST(N'2001-04-29' AS Date), NULL, NULL, NULL, NULL, 11, N'57', 1, 1, 6, 20, 300, 1, NULL, NULL, CAST(N'2022-07-01' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (104, N'Christensen', N'Jakob', CAST(N'2001-06-25' AS Date), NULL, NULL, NULL, NULL, 11, N'57', 1, 1, 22, 4, 300, 0, NULL, NULL, CAST(N'2023-07-01' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (106, N'Diehl', N'Justin', CAST(N'2004-11-27' AS Date), NULL, NULL, NULL, NULL, 11, N'57', 1, 1, 49, 5, 300, 0, NULL, NULL, CAST(N'2023-07-01' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (108, N'Casteels', N'Koen', CAST(N'1992-06-25' AS Date), NULL, NULL, NULL, NULL, 8, N'57', 1, 1, 1, 19, 300, 0, NULL, NULL, CAST(N'2015-07-01' AS Date), 1, N'Torhüter                                          ', 1)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (109, N'Bornauw', N'Sebastiaan ', CAST(N'1999-03-22' AS Date), NULL, NULL, NULL, NULL, 8, N'57', 1, 1, 3, 12, 300, 0, NULL, NULL, CAST(N'2021-07-16' AS Date), 1, N'Abwehr                                            ', 2)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (110, N'Maehle', N'Joakim ', CAST(N'1997-05-20' AS Date), NULL, NULL, NULL, NULL, 8, N'57', 1, 1, 21, 22, 300, 1, NULL, NULL, CAST(N'2023-08-12' AS Date), 1, N'Abwehr                                            ', 2)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (111, N'Lacroix', N'Maxence ', CAST(N'2000-04-06' AS Date), NULL, NULL, NULL, NULL, 8, N'57', 1, 1, 4, 19, 300, 2, NULL, NULL, CAST(N'2020-08-25' AS Date), 1, N'Abwehr                                            ', 2)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (112, N'Jenz', N'Moritz ', CAST(N'1999-04-30' AS Date), NULL, NULL, NULL, NULL, 8, N'57', 1, 1, 25, 16, 300, 0, NULL, NULL, CAST(N'2023-07-01' AS Date), 1, N'Abwehr                                            ', 3)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (113, N'Zesiger', N'Cedric', CAST(N'1998-06-24' AS Date), NULL, NULL, NULL, NULL, 8, N'57', 1, 1, 5, 14, 300, 0, NULL, NULL, CAST(N'2023-07-01' AS Date), 0, N'Abwehr                                            ', 2)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (114, N'Arnold', N'Maximilian', CAST(N'1994-05-27' AS Date), NULL, NULL, NULL, NULL, 8, N'57', 1, 1, 27, 19, 300, 1, NULL, NULL, CAST(N'2009-07-01' AS Date), 1, N'Mittelfeld                                        ', 3)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (115, N'Cerny', N'Vaclav ', CAST(N'1997-10-17' AS Date), NULL, NULL, NULL, NULL, 8, N'57', 1, 1, 7, 17, 300, 3, NULL, NULL, CAST(N'2023-07-01' AS Date), 1, N'Mittelfeld                                        ', 3)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (116, N'Svanberg', N'Mattias ', CAST(N'1999-01-05' AS Date), NULL, NULL, NULL, NULL, 8, N'57', 1, 1, 32, 20, 300, 1, NULL, NULL, CAST(N'2022-07-16' AS Date), 1, N'Mittelfeld                                        ', 3)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (117, N'Vranckx', N'Aster', CAST(N'2002-10-04' AS Date), NULL, NULL, NULL, NULL, 8, N'57', 1, 1, 6, 16, 300, 0, NULL, NULL, CAST(N'2023-07-01' AS Date), 1, N'Mittelfeld                                        ', 3)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (118, N'Wimmer', N'Patrick', CAST(N'2001-05-30' AS Date), NULL, NULL, NULL, NULL, 8, N'57', 1, 1, 39, 7, 300, 0, NULL, NULL, CAST(N'2022-07-01' AS Date), 1, N'Mittelfeld                                        ', 3)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (81, N'Stöger', N'Kevin', CAST(N'1993-08-27' AS Date), NULL, NULL, NULL, NULL, 14, N'57', 1, 1, 7, 20, 300, 5, NULL, NULL, CAST(N'2022-07-01' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (82, N'Asano', N'Takuma ', CAST(N'1994-11-10' AS Date), NULL, NULL, NULL, NULL, 14, N'57', 1, 1, 11, 18, 300, 6, NULL, NULL, CAST(N'2021-07-01' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (96, N'Maina', N'Linton ', CAST(N'1999-06-23' AS Date), NULL, NULL, NULL, NULL, 11, N'57', 1, 1, 37, 20, 300, 1, NULL, NULL, CAST(N'2022-07-01' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (97, N'Thielmann', N'Jan', CAST(N'2002-05-26' AS Date), NULL, NULL, NULL, NULL, 11, N'57', 1, 1, 29, 14, 300, 1, NULL, NULL, CAST(N'2017-07-01' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (105, N'Waeschenbach', N'Meiko', CAST(N'2004-01-13' AS Date), NULL, NULL, NULL, NULL, 11, N'57', 1, 1, 36, 0, 300, 0, NULL, NULL, CAST(N'2023-07-01' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (107, N'Dietz', N'Florian', CAST(N'1998-08-03' AS Date), NULL, NULL, NULL, NULL, 11, N'57', 1, 1, 33, 4, 300, 0, NULL, NULL, CAST(N'2020-08-10' AS Date), 1, NULL, 999)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (119, N'Paredes', N'Kevin', CAST(N'2003-05-07' AS Date), NULL, NULL, NULL, NULL, 8, N'57', 1, 1, 40, 19, 300, 2, NULL, NULL, CAST(N'2023-01-28' AS Date), 1, N'Mittelfeld                                        ', 3)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (120, N'Kaminski', N'Jakub', CAST(N'2002-06-05' AS Date), NULL, NULL, NULL, NULL, 8, N'57', 1, 1, 16, 13, 300, 0, NULL, NULL, CAST(N'2022-07-01' AS Date), 1, N'Mittelfeld                                        ', 3)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (121, N'Behrens', N'Kevin', CAST(N'1991-03-02' AS Date), NULL, NULL, NULL, NULL, 8, N'57', 1, 1, 17, 4, 300, 1, NULL, NULL, CAST(N'2024-01-31' AS Date), 1, N'Sturm                                             ', 4)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (122, N'Nmecha', N'Lukas', CAST(N'1998-12-14' AS Date), NULL, NULL, NULL, NULL, 8, N'57', 1, 1, 10, 2, 300, 0, NULL, NULL, CAST(N'2021-07-16' AS Date), 1, N'Sturm                                             ', 4)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (123, N'Sarr', N'Amin', CAST(N'2001-03-11' AS Date), NULL, NULL, NULL, NULL, 8, N'57', 1, 1, 9, 7, 300, 0, NULL, NULL, CAST(N'2023-08-31' AS Date), 0, N'Sturm                                             ', 4)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (124, N'Oliveira da Silva', N'Rogerio ', CAST(N'1998-01-13' AS Date), NULL, NULL, NULL, NULL, 8, N'57', 1, 1, 13, 12, 300, 1, NULL, NULL, CAST(N'2023-08-05' AS Date), 1, N'Abwehr                                            ', 2)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (125, N'Müller', N'Kevin', CAST(N'1991-03-15' AS Date), NULL, NULL, NULL, NULL, 18, N'57', 1, 1, 32, 23, 300, 0, NULL, NULL, CAST(N'2015-07-01' AS Date), 1, N'Torhüter                                          ', 1)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (126, N'Busch', N'Marnon', CAST(N'1994-12-08' AS Date), NULL, NULL, NULL, NULL, 18, N'57', 1, 1, 2, 10, 300, 0, NULL, NULL, CAST(N'2017-07-01' AS Date), 1, N'Abwehr                                            ', 2)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (127, N'Föhrenbach', N'Jonas', CAST(N'1996-01-26' AS Date), NULL, NULL, NULL, NULL, 18, N'57', 1, 1, 19, 22, 300, 0, NULL, NULL, CAST(N'2019-07-01' AS Date), 1, N'Abwehr                                            ', 2)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (128, N'Mainka', N'Patrick', CAST(N'1994-11-06' AS Date), NULL, NULL, NULL, NULL, 18, N'57', 1, 1, 6, 23, 300, 2, NULL, NULL, CAST(N'2018-07-01' AS Date), 1, N'Abwehr                                            ', 2)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (129, N'Siersleben', N'Tim', CAST(N'2000-03-09' AS Date), NULL, NULL, NULL, NULL, 18, N'57', 1, 1, 4, 13, 300, 0, NULL, NULL, CAST(N'2021-07-01' AS Date), 1, N'Abwehr                                            ', 2)
GO
INSERT [dbo].[Kader] ([Id], [SpielerName], [Vorname], [Geburtstag], [Groesse], [Gewicht], [Laenderspiele], [LaenderspieleTore], [VereinNr], [LandID], [SaisonID], [LigaID], [Rueckennummer], [Einsaetze], [Spielminuten], [Tore], [Abloesesumme], [Image], [ImVereinSeit], [Aktiv], [Position], [PositionsNr]) VALUES (130, N'Traoré', N'Omar Haktab', CAST(N'1998-02-04' AS Date), NULL, NULL, NULL, NULL, 18, N'57', 1, 1, 23, 21, 300, 0, NULL, NULL, CAST(N'2023-07-01' AS Date), 1, N'Abwehr                                            ', 2)
GO
SET IDENTITY_INSERT [dbo].[Spieler] OFF
GO
